version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: factura-postgres
    environment:
      POSTGRES_DB: factura_db
      POSTGRES_USER: factura_user
      POSTGRES_PASSWORD: Factura123!
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: factura-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@factura.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
